[package]
name = "editor-iul"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "*"
syntect = { version = "5", optional = true, default-features = false, features = [
    "default-fancy",
] }
